spring.application.name=voting-system
spring.datasource.url=jdbc:postgresql://localhost:5333/vote-sys
spring.datasource.username=omarscode
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE